ADP-242
harecode-ar/ADP pull request #210
Opened 2024-01-10 04:44 UTC by lucaslezano

Quitar el signo $ del final del input de costo proyectado
![image](https://github.com/harecode-ar/ADP/assets/72807139/8f5d4230-e912-4a68-a75d-8b139c62aaa8)

2024-01-10 16:15 UTC, martinfacc requested changes
❌ Como dice pablito en el comentario, hay que dejar el endAdornment y quitar el signo "$" del string

2024-01-10 18:57 UTC, lucaslezano commented
Porque lo dice pablito nomas lo hago...

2024-01-10 23:11 UTC, martinfacc requested changes
❌ No es necesario agregar tantas funciones extras, porque despues son dificil de mantener. Usa el metodo .replace solamente para quitar el signo de pesos:
```jsx
value={formatCost(project.cost).replace('$', '')}
```

2024-01-11 03:23 UTC, martinfacc commented on packages/frontend/src/utils/format-number.ts
> +  if (!value) return '0'
Ojo aca que borraste el signo "$"

2024-01-11 03:24 UTC, martinfacc commented on packages/frontend/src/sections/project/nuevo/create-project.tsx
> +import { formatCost } from 'src/utils/format-number'
Este import esta de mas porque no se usa

2024-01-11 04:06 UTC, martinfacc approved these changes
👌

2024-01-11 04:07 UTC, merged